bank_sync:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: actualbudget

budget_sync:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: actualbudget